/**
 * wikiWorker.js
 * Runs daily to auto-generate/update community wiki pages from top-scoring posts.
 * Groups posts by category, selects the top 10 per category, upserts WikiPage docs.
 */

const Post = require('../models/Post');
const WikiPage = require('../models/WikiPage');
const { generateWikiDescription } = require('../services/knowledgeAiService');

const WIKI_SCORE_THRESHOLD = parseInt(process.env.WIKI_SCORE_THRESHOLD || '10', 10);
const MAX_POSTS_PER_WIKI = 10;
const WORKER_INTERVAL_MS = 24 * 60 * 60 * 1000; // 24 hours

// Convert a category string to a URL slug
function toSlug(str) {
    return String(str)
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .slice(0, 80);
}

async function runWikiGeneration() {
    console.log('[WikiWorker] Starting wiki generation run...');
    try {
        // Aggregate top posts by category
        const topPostsByCategory = await Post.aggregate([
            {
                $match: {
                    deletedAt: null,
                    isVisible: true,
                    isAnonymous: false,
                    score: { $gte: WIKI_SCORE_THRESHOLD },
                    $or: [
                        { unlocksAt: null },
                        { unlocksAt: { $lte: new Date() } },
                    ],
                },
            },
            { $sort: { score: -1 } },
            {
                $group: {
                    _id: '$category',
                    posts: {
                        $push: {
                            postId: '$_id',
                            score: '$score',
                            caption: '$caption',
                            image_url: '$image_url',
                        },
                    },
                },
            },
            { $match: { _id: { $ne: null } } },
        ]);

        let created = 0;
        let updated = 0;

        for (const group of topPostsByCategory) {
            const category = group._id;
            if (!category) continue;

            const slug = toSlug(category);
            if (!slug) continue;

            // Take top N posts
            const topPosts = group.posts.slice(0, MAX_POSTS_PER_WIKI).map(p => ({
                postId: p.postId,
                score: p.score,
                addedBy: 'auto',
                addedAt: new Date(),
            }));

            const sampleCaptions = group.posts
                .slice(0, 5)
                .map(p => p.caption)
                .filter(Boolean);

            // Check if wiki page exists
            const existing = await WikiPage.findOne({ slug });

            if (!existing) {
                // Generate AI description for new wiki pages
                let description = '';
                try {
                    description = await generateWikiDescription(category, sampleCaptions);
                } catch (_) { /* graceful degradation */ }

                // Pick cover image from first post that has one
                const coverImage = group.posts.find(p => p.image_url)?.image_url || null;

                await WikiPage.create({
                    slug,
                    topic: category,
                    description,
                    coverImage,
                    topPosts,
                    isAutoGenerated: true,
                    isPublished: true,
                    scoreThreshold: WIKI_SCORE_THRESHOLD,
                    lastUpdated: new Date(),
                });
                created++;
            } else {
                // Merge community suggestions with new auto-picks
                // Keep community-contributed posts, update auto ones
                const communityPosts = existing.topPosts.filter(p => p.addedBy === 'community');
                const autoPosts = topPosts.filter(
                    tp => !communityPosts.some(cp => cp.postId.toString() === tp.postId.toString())
                );

                const merged = [...communityPosts, ...autoPosts]
                    .sort((a, b) => b.score - a.score)
                    .slice(0, MAX_POSTS_PER_WIKI);

                await WikiPage.findByIdAndUpdate(existing._id, {
                    $set: {
                        topPosts: merged,
                        lastUpdated: new Date(),
                    },
                });
                updated++;
            }
        }

        console.log(`[WikiWorker] Done: ${created} created, ${updated} updated (threshold=${WIKI_SCORE_THRESHOLD})`);
    } catch (err) {
        console.error('[WikiWorker] Generation failed:', err.message);
    }
}

let _wikiInterval = null;

async function initWikiWorker() {
    try {
        // Run once immediately at startup
        await runWikiGeneration();

        // Then schedule to run every 24 hours
        _wikiInterval = setInterval(runWikiGeneration, WORKER_INTERVAL_MS);
        console.log('[WikiWorker] Initialized — runs every 24h');
    } catch (err) {
        console.warn('[WikiWorker] Init failed:', err.message);
    }
}

function stopWikiWorker() {
    if (_wikiInterval) clearInterval(_wikiInterval);
}

module.exports = { initWikiWorker, stopWikiWorker, runWikiGeneration };
