const mongoose = require('mongoose');

/**
 * WikiPage — community-driven topic wiki pages.
 * Auto-generated from top posts (score >= threshold) by the wikiWorker.
 * Can also be contributed to manually by users.
 */
const WikiPostEntrySchema = new mongoose.Schema(
  {
    postId: { type: mongoose.Schema.Types.ObjectId, ref: 'Post', required: true },
    score: { type: Number, default: 0 },
    addedAt: { type: Date, default: Date.now },
    addedBy: { type: String, enum: ['auto', 'community'], default: 'auto' },
    suggestedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  },
  { _id: false }
);

const WikiPageSchema = new mongoose.Schema(
  {
    // URL-friendly topic slug (e.g. "technology", "mental-health")
    slug: { type: String, unique: true, required: true, lowercase: true, trim: true },

    // Display name (e.g. "Technology", "Mental Health")
    topic: { type: String, required: true },

    // AI-generated introduction paragraph
    description: { type: String, default: '' },

    // Cover image URL (auto-picked from a top post or AI-generated)
    coverImage: { type: String, default: null },

    // Top posts curated for this wiki (max 20)
    topPosts: [WikiPostEntrySchema],

    // Users who have suggested posts for this wiki
    contributors: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],

    // true = auto-generated by worker; false = manually created
    isAutoGenerated: { type: Boolean, default: true },

    // Whether this wiki is publicly visible
    isPublished: { type: Boolean, default: true },

    // Analytics
    viewCount: { type: Number, default: 0 },

    // Minimum post score required to auto-qualify for this wiki
    scoreThreshold: { type: Number, default: 50 },

    lastUpdated: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

WikiPageSchema.index({ isPublished: 1, viewCount: -1 });
WikiPageSchema.index({ 'topPosts.postId': 1 });

module.exports = mongoose.model('WikiPage', WikiPageSchema);
